### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by TheYoBots** [romainbutteaud/Kaffeine#46]
Does this restart all dynos every 30 minutes or does it deploy the bot every 30 minutes?

Also would be nice if users could increase/decrease the time from 30 minutes to a custom value.

Thanks!

**Comment by gyz15** [comment]
> Does this restart all dynos every 30 minutes or does it deploy the bot every 30 minutes?
> 
> Also would be nice if users could increase/decrease the time from 30 minutes to a custom value.
> 
> Thanks!


I think it doesn't restart your dynos every 30 minutes but prentending a request to your heroku app so it will always stays active and does not sleep every one hour due to no traffic.

I think you may consider using [cronjob](https://cron-job.org/en/) as another method to prevent your app goes sleep. 

More information on this [article](https://betterprogramming.pub/keeping-my-heroku-app-alive-b19f3a8c3a82).

**Comment by TheYoBots** [comment]
Thanks for your response. Things have been clarified now :)
